ServerEvents.recipes(Receita => 
    {
        Receita.remove({id: "mekanism:processing/gold/dust/from_raw_ore"})
        Receita.remove({id: "mekanism:processing/iron/dust/from_raw_ore"})
        Receita.remove({id: "mekanism:processing/osmium/dust/from_raw_ore"})
        Receita.remove({id: "mekanism:processing/tin/dust/from_raw_ore"})
        Receita.remove({id: "mekanism:processing/uranium/dust/from_raw_ore"})
        Receita.remove({id: "mekanism:processing/lead/dust/from_raw_ore"})
        Receita.remove({id: "mekanism:processing/copper/dust/from_raw_ore"})
        Receita.remove({id: "allthemodium:mek_processing/allthemodium/dust/from_raw_ore"})
        Receita.remove({id: "allthemodium:mek_processing/vibranium/dust/from_raw_ore"})
        Receita.remove({id: "allthemodium:mek_processing/unobtainium/dust/from_raw_ore"})
        Receita.remove({output: "minecraft:polished_diorite", id: "mekanism:enriching/conversion/diorite/to_polished",})
        Receita.remove({id: "alltheores:mek_processing/aluminum/dust/from_raw_ore"})
        Receita.remove({id: "alltheores:mek_processing/nickel/dust/from_raw_ore",})
        Receita.remove({id: "alltheores:mek_processing/platinum/dust/from_raw_ore",})
        Receita.remove({id: "alltheores:mek_processing/silver/dust/from_raw_ore",})
        Receita.remove({id: "alltheores:mek_processing/iridium/dust/from_raw_ore",})
        Receita.remove({id: "alltheores:mek_processing/zinc/dust/from_raw_ore",})
    
    })